export const TownsDb: string[] = [
  "Aguascalientes",
  "Tijuana",
  "La Paz",
  "Carmen",
  "Tuxtla Gutiérrez",
  "Chihuahua",
  "Guadalupe",
  "Zacatecas",
  "Cuernavaca",
  "Puebla",
  "Oaxaca de Juárez",
  "León",
  "Morelia",
  "Tepic",
  "Monterrey",
  "Mazatlán",
  "Tampico",
  "Cancún",
  "Campeche",
  "Colima",
  "Durango",
  "Acapulco",
  "Mérida",
  "Querétaro",
  "Toluca",
  "San Luis Potosí",
  "Villahermosa",
  "Tlaxcala",
  "Chetumal",
  "Hermosillo",
  "Guadalajara",
];
